name: reasa
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.0.3
  google_fonts: ^2.2.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  intl_phone_field: ^3.0.1
  flutter_spinkit: ^5.1.0
  flutter_otp_text_field: ^1.1.0
  pin_code_fields: ^7.4.0
  iconly: ^1.0.1
  chip_list: ^2.3.3+8
  syncfusion_flutter_sliders: ^20.2.45
  syncfusion_flutter_core: ^20.2.45
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_datepicker: ^20.2.46
  flutter_switch: ^0.3.2
  url_launcher: ^6.1.5
  
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^10.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

