// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU7imDuFw9TyaXh95OHg2i4zykJgs7bNQ',
    appId: '1:811029168672:web:1338babbb54f43f85f7245',
    messagingSenderId: '811029168672',
    projectId: 'escan-7127b',
    authDomain: 'escan-7127b.firebaseapp.com',
    storageBucket: 'escan-7127b.appspot.com',
    measurementId: 'G-5ZRCSM2F2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABE_is7xr1SsQiI8dNjH14H1i1tB_FpZE',
    appId: '1:811029168672:android:99a0afad4b401b4b5f7245',
    messagingSenderId: '811029168672',
    projectId: 'escan-7127b',
    storageBucket: 'escan-7127b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7bmye69lZDmmaBdpxkr4k6qCNSeg5l9E',
    appId: '1:811029168672:ios:d89b58adf18701735f7245',
    messagingSenderId: '811029168672',
    projectId: 'escan-7127b',
    storageBucket: 'escan-7127b.appspot.com',
    iosClientId: '811029168672-7sbtnjc9leu0o0ev3n3g2jun2so7okcp.apps.googleusercontent.com',
    iosBundleId: 'com.reasa.reasa',
  );
}
